config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  resources :books do
    member do
      post 'draft'
      post 'publish'
    end
  end

  namespace :admin do
    get 'dashboard/index'
    root 'dashboard#index'

    resources :genres
    resources :books do
      member do
        post 'draft'
        post 'publish'
      end
    end
  end

  root 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  include AASM

  friendly_id :slug_candidates, use: [:finders, :slugged]

  aasm do
    state :publish, initial: true
    state :draft

    event :publishing do
      transitions from: :draft, to: :publish
    end

    event :drafting do
      transitions from: :publish, to: :draft
    end
  end

  validates :title, :author, presence: true
  validates :logo, format: { with: /\Ahttps?:\/\/.*\.(?:jpe?g|png|gif)\z/,
    message: 'can be only image URL in jpeg, gif or png format'  }

  belongs_to :user
  has_and_belongs_to_many :genres

  scope :recents, -> { where('created_at >= ?', 1.week.ago) }
  default_scope -> { order(id: :desc) }

  private

  def slug_candidates
    [
      :title,
      [:title, :author]
    ]
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :draft]
  before_action :set_genres, only: [:new, :edit, :create, :update]

  def index
    @books = Book.all.page(params[:page])
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to admin_books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to admin_books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to admin_books_path, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    @book.publishing!
    redirect_to admin_books_path, notice: 'State is updated'
  end

  def draft
    @book.drafting!
    redirect_to admin_books_path, notice: 'State is updated'
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def set_genres
      @genres = Genre.all
    end

    def book_params
      params.require(:book).permit(:title, :author, :logo, :description, :user_id,
                                   genre_ids: [])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :draft]
  before_action :set_genres, only: [:new, :edit, :create, :update]

  # GET /books
  # GET /books.json
  def index
    @books = if params[:my]
              current_user.books.page(params[:page])
             else
              Book.recents.page(params[:page])
             end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    authorize @book
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize @book

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize @book

    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    authorize @book

    @book.publishing!
    redirect_back 'Status is updated'
  end

  def draft
    authorize @book

    @book.drafting!
    redirect_back 'Status is updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_genres
      @genres = Genre.all
    end

    def check_owner
      redirect_to root_path, notice: 'Oops' unless @book.user == current_user
    end

    def redirect_back(notice)
      redirect_to(request.referrer || root_path, notice: notice)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :logo, :description,
                                   genre_ids: [])
    end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def admin_state_link(book)
    if book.draft?
      link_to 'To publish', publish_admin_book_path(book),
                            method: :post,
                            class: "btn btn-success"
    else
      link_to 'To draft', draft_admin_book_path(book),
                          method: :post,
                          class: "btn btn-warning"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def owner_actions?(book)
    policy(book).edit? && policy(book).destroy?
  end

  def state_link(book)
    if book.draft?
      link_to 'To publish', publish_book_path(book),
                            method: :post,
                            class: "btn btn-success"
    else
      link_to 'To draft', draft_book_path(book),
                          method: :post,
                          class: "btn btn-warning"
    end
  end

  def books_active_class(key)
    case key
    when 'all'
      params['my'] ? '' : 'active'
    when 'my'
      params['my'] ? 'active' : ''
    end
  end
end

app/views/admin/books/_form.html.erb
<%= form_for([:admin, book], html: { class: 'form-horizontal' }) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <label for="book_title" class="col-lg-2 control-label">Title</label>
    <div class="col-lg-5">
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="book_author" class="col-lg-2 control-label">Author</label>
    <div class="col-lg-5">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="book_logo" class="col-lg-2 control-label">Logo</label>
    <div class="col-lg-5">
      <%= f.text_field :logo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="book_description" class="col-lg-2 control-label">Description</label>
    <div class="col-lg-5">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="book_description" class="col-lg-2 control-label">Genre</label>
    <div class="col-lg-5">
      <%= f.collection_select(:genre_ids,
                            @genres, :id, :title,
                            { selected: @book.genre_ids },
                            { multiple: true, class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <label for="book_user_id" class="col-lg-2 control-label">User ID</label>
    <div class="col-lg-5">
      <%= f.text_field :user_id, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <span class="col-lg-2 control-label"></span>
    <div class="col-lg-2">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_books_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

app/views/admin/books/index.html.erb
<h1>Books dashboard
  <%= link_to 'New Book', new_admin_book_path, class: 'btn btn-primary' %>
</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Logo</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= image_tag(book.logo, size: "240x320") %></td>
        <td><%= link_to 'Show', admin_book_path(book), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_admin_book_path(book), class: 'btn btn-info' %></td>
        <td><%= admin_state_link(book) %></td>
        <td><%= link_to 'Delete', admin_book_path(book),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @books %>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

app/views/admin/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @book.logo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>