config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  resources :books do
    member do
      post 'draft'
      post 'publish'
    end
  end

  namespace :admin do
    get 'dashboard/index'
    root 'dashboard#index'

    resources :genres
    resources :books do
      member do
        post 'draft'
        post 'publish'
      end
    end
  end

  root 'books#index'
end

app/views/shared/_admin_nav.html.erb
<ul class="nav nav-pills">
  <li><%= link_to 'Dashboard', admin_root_path %></li>
  <li><%= link_to 'Books', admin_books_path %></li>
  <li><%= link_to 'Genres', admin_genres_path %></li>
</ul>

app/views/shared/_admin_user_nav.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User actions <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to 'Edit profile', edit_admin_user_registration_path %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Sign out', destroy_admin_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/shared/_flash_messagess.html.erb
<div id="flash_messages">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Books', root_path, class: 'navbar-brand' %>
    </div>
    <%= render 'shared/user_nav' if current_user %>
    <%= render 'shared/admin_user_nav' if current_admin_user %>
  </div>
</nav>

app/views/shared/_user_nav.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User actions <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to 'Edit profile', edit_user_registration_path %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
</div>