config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  resources :books do
    member do
      post 'draft'
      post 'publish'
    end
  end

  namespace :admin do
    get 'dashboard/index'
    root 'dashboard#index'

    resources :genres
    resources :books do
      member do
        post 'draft'
        post 'publish'
      end
    end
  end

  root 'books#index'
end

app/models/genre.rb
class Genre < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:finders, :slugged, :history]

  default_scope -> { order(id: :desc) }
  validates :title, presence: true

  has_and_belongs_to_many :books

  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all.page(params[:page])
  end

  def show
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to admin_genres_path, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to admin_genres_path, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to admin_genres_path, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end

    def genre_params
      params.require(:genre).permit(:title)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_for([:admin, genre], html: { class: 'form-horizontal' }) do |f| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <label for="genre_title" class="col-lg-2 control-label">Title</label>
    <div class="col-lg-5">
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <span class="col-lg-2 control-label"></span>
    <div class="col-lg-2">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_genres_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

app/views/admin/genres/index.html.erb
<h1>Genres dashboard
  <%= link_to 'New Genre', new_admin_genre_path, class: 'btn btn-primary' %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.title %></td>
        <td><%= genre.slug %></td>
        <td><%= link_to 'Show', admin_genre_path(genre), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_admin_genre_path(genre), class: 'btn btn-info' %></td>
        <td><%= link_to 'Delete', admin_genre_path(genre),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @genres %>

app/views/admin/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

app/views/admin/genres/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @genre.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @genre.slug %>
</p>

<%= link_to 'Edit', edit_admin_genre_path(@genre) %> |
<%= link_to 'Back', admin_genres_path %>